---
title: "p8105_hw6_mm5351"
author: "Martha Mulugeta"
date: "11/15/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colur_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)
```

**Problem 1**
```{r load/tidy data}
birthweight_data = 
  read_csv("./Data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = recode(babysex, 
              "1" = "male", 
              "2" = "female"),
  babysex = as.factor(babysex),
  frace = recode(frace,
                 "1" = "White",
                 "2" = "Black",
                 "3" = "Asian",
                 "4" = "Puerto Rican",
                 "8" = "Other",
                 "9" = "Unknown"),
  frace = as.factor(frace),
  malform = recode(malform,
                   "0" = "absent",
                   "1" = "present"),
  malform = as.factor(malform),
  mrace = recode(mrace,
                 "1" = "White",
                 "2" = "Black",
                 "3" = "Asian",
                 "4" = "Puerto Rican",
                 "8" = "Other"),
  mrace = as.factor(mrace)) %>% 
  na.omit()
```

```{r models}
model1 = lm(bwt ~ fincome + momage, data = birthweight_data) 

model1 %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)

modelr::add_residuals(birthweight_data, model1) %>% 
modelr::add_predictions(model1) %>% 
ggplot(aes(x = pred, y = resid)) +
  geom_point()

```

```{r}
model2 = 
  lm(bwt ~ blength + gaweeks, data = birthweight_data) %>% 
  broom::tidy()

model3 = 
  lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = birthweight_data) %>% 
  broom::tidy()
```

```{r}
cv_df = 
  crossv_mc(birthweight_data, 100)

cv_df %>% pull(train) %>% .[[1]] %>% as_tibble
cv_df %>% pull(test) %>% .[[1]] %>% as_tibble

cv_df =
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(model1  = map(train, ~lm(bwt ~ fincome + momage, data = birthweight_data)),
         model2  = map(train, ~lm(bwt ~ blength + gaweeks, data = birthweight_data)),
         model3  = map(train, ~ lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = birthweight_data))) %>% 
  mutate(rmse_model1 = map2_dbl(model1, test, ~rmse(model = .x, data = .y)),
         rmse_model2 = map2_dbl(model2, test, ~rmse(model = .x, data = .y)),
         rmse_model3 = map2_dbl(model3, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

***Problem 2***
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
bootstrap_rsquared = 
  weather_df %>%
  modelr::bootstrap(n = 5000) %>%
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)) %>% 
  select(results) %>% 
  unnest(results) %>% 
  mutate(
    lower = quantile(r.squared, 0.025),
    upper = quantile(r.squared, 0.975)
  ) %>% 
  select(lower, upper) %>% 
  distinct()
```

The 95% confidence interval for r-squared is between `r pull(bootstrap_rsquared, lower)` and `r pull(bootstrap_rsquared, upper)`.

```{r}
bootstrap_log = 
  weather_df %>%
  modelr::bootstrap(n = 5000) %>%
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(results) %>% 
  unnest(results) %>%
  select(term, estimate) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  unnest() %>% 
  rename("intercept" = "(Intercept)") %>% 
  mutate(logb0b1 = log(intercept * tmin),
    lower = quantile(logb0b1, 0.025),
    upper = quantile(logb0b1, 0.975)
  ) %>% 
  select(lower, upper) %>% 
  distinct()
```

The 95% confidence interval for log(b0 * b1) is between `r pull(bootstrap_log, lower)` and `r pull(bootstrap_log, upper)`.


